<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
	<link rel="stylesheet" type="text/css" href="pirate-dark.css"/>
	<title>Pirate Cuisine</title>
</head>

<body>
<div id="topmenu">
	<p>

		<a class="active" href="index.php">Bar</a>
		<a href="index.php?menu=1">Salmagundi</a>
		<a href="index.php?menu=2">Rum</a>
		<a href="index.php?menu=3">Bumbo</a>
		<a href="index.php?menu=4">Punch</a>
		<a href="index.php?menu=5">Kashiri</a>
	</p>
</div>

<div id="header">
	<div id="title">
		<h1><a href="index.php">Pirate Bar</a></h1>
		<img src="pirat2.jpg">
	</div>
</div>

	<div id="content">
		<div class="post">