<br><br><br><br><br><br><br><br><br><br><br><br>
       </div>
    </div>
    <!-- end main -->
    <!-- footer -->
    <div id="footer">
    <div id="left_footer">&copy; Copyright 2012 BlackBuilding Media</div>
    <div id="right_footer">

<span style="visibility: hidden">
<a href="c_panel.php">for coders</a>
</span>

    </div>
    </div>
    <!-- end footer -->
</div>
</body>
</html>
