<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>Build Your Media</title>
<link href="style.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div id="container">
	<!-- header -->
    <div id="header">
    	<div id="logo"><a href="#"><span class="orange">BlackBuilding</span> Media</a></div>
        <div id="menu">
        	<ul>
            <li><a href="index.php?id=1" class="active">home</a></li>
            <li><a href="index.php?id=2">about us</a></li>
            <li><a href="index.php?id=3">clients</a></li>
            <li><a href="index.php?id=4">contacts</a></li>
            </ul>
        </div>
    </div>
    <!--end header -->
    <!-- main -->
    <div id="main">
        <div id="content">
        <div id="head_image">
        	<div id="slogan">Building<strong> your</strong> ideas</div>
            <div id="under_slogan_text">for all world</div>
        </div>
		        <div id="text">